[package]
name = "financial-planner-cli"
version = "0.1.0"
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]

[dependencies]
num = "0.1"
clap = "2"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
chrono = { version = "0.3", features = ["serde"] }
prettytable-rs = "^0.6"
